if getActivatedMods():contains("ItemTweakerAPI") then
	require("ItemTweaker_Core");
else return end

-- TORSO EXTRA
TweakItemData["Base.Vest_Hunting_Camo"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Vest_BulletCivilian"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jumper_TankTopDiamondTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Vest_Foreman"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Vest_Waistcoat_GigaMart"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Vest_Hunting_Grey"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Vest_Hunting_CamoGreen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Vest_HighVis"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Vest_BulletArmy"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Vest_Hunting_Orange"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Vest_BulletPolice"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jumper_TankTopTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Vest_Waistcoat"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Vest_WaistcoatTINT"] = { ["Weight"] = "0.1" };

-- JACKETS
TweakItemData["Base.WeddingJacket"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Ghillie_Top"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Suit_Jacket"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jacket_Varsity"] = { ["Weight"] = "0.1" };
TweakItemData["Base.JacketLong_Doctor"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jacket_CoatArmy"] = { ["Weight"] = "0.1" };
TweakItemData["Base.JacketLong_Random"] = { ["Weight"] = "0.1" };
TweakItemData["Base.JacketLong_Santa"] = { ["Weight"] = "0.1" };
TweakItemData["Base.JacketLong_SantaGreen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jacket_ArmyCamoDesert"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jacket_ArmyCamoGreen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jacket_Black"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jacket_Chef"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jacket_Fireman"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jacket_PaddedDOWN"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jacket_Police"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jacket_Ranger"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jacket_WhiteTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jumper_DiamondPatternTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jumper_PoloNeck"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jumper_RoundNeck"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jumper_VNeck"] = { ["Weight"] = "0.1" };
TweakItemData["Base.HoodieDOWN_WhiteTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.HoodieUP_WhiteTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.PonchoGreen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.PonchoYellow"] = { ["Weight"] = "0.1" };
TweakItemData["Base.PonchoGreenDOWN"] = { ["Weight"] = "0.1" };
TweakItemData["Base.PonchoYellowDOWN"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Jacket_NavyBlue"] = { ["Weight"] = "0.1" };

-- BELTS
TweakItemData["Base.Belt2"] = { ["Weight"] = "0.1" };
TweakItemData["Base.AmmoStrap_Bullets"] = { ["Weight"] = "0.1" };
TweakItemData["Base.HolsterDouble"] = { ["Weight"] = "0.1" };
TweakItemData["Base.HolsterSimple"] = { ["Weight"] = "0.1" };
TweakItemData["Base.AmmoStrap_Shells"] = { ["Weight"] = "0.1" };

-- LEGS
TweakItemData["Base.LongJohns_Bottoms"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shorts_CamoGreenLong"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shorts_LongDenim"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shorts_LongSport"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shorts_LongSport_Red"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shorts_ShortDenim"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shorts_ShortFormal"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shorts_ShortSport"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Skirt_Knees"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Skirt_Knees"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Skirt_Normal"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Skirt_Short"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Ghillie_Trousers"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers"] = { ["Weight"] = "0.1" };
TweakItemData["Base.TrousersMesh_DenimLight"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_CamoDesert"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_CamoGreen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_CamoUrban"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_Chef"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_DefaultTEXTURE"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_DefaultTEXTURE_HUE"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_DefaultTEXTURE_TINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_Denim"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_Fireman"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_JeanBaggy"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_Padded"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_Police"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_PoliceGrey"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_PrisonGuard"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_Ranger"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_Santa"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_SantaGReen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_Scrubs"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_Suit"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_SuitTEXTURE"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_SuitWhite"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_WhiteTEXTURE"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_WhiteTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Dungarees"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_ArmyService"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_Black"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Trousers_NavyBlue"] = { ["Weight"] = "0.1" };

-- FEET
TweakItemData["Base.Socks_Long"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Socks_Ankle"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shoes_BlackBoots"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shoes_FlipFlop"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shoes_ArmyBoots"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shoes_ArmyBootsDesert"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shoes_Wellies"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shoes_RidingBoots"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shoes_Black"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shoes_Brown"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shoes_Random"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shoes_Slippers"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shoes_RedTrainers"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shoes_BlueTrainers"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shoes_TrainerTINT"] = { ["Weight"] = "0.1" };

-- SUIT
TweakItemData["Base.Boilersuit_Flying"] = { ["Weight"] = "0.1" };
TweakItemData["Base.LongCoat_Bathrobe"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Boilersuit"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Boilersuit_BlueRed"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Dress_Normal"] = { ["Weight"] = "0.1" };
TweakItemData["Base.HazmatSuit"] = { ["Weight"] = "0.1" };
TweakItemData["Base.HospitalGown"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Dress_Knee"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Dress_Long"] = { ["Weight"] = "0.1" };
TweakItemData["Base.LongJohns"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Boilersuit_Prisoner"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Boilersuit_PrisonerKhaki"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Dress_Short"] = { ["Weight"] = "0.1" };
TweakItemData["Base.SpiffoSuit"] = { ["Weight"] = "0.1" };
TweakItemData["Base.WeddingDress"] = { ["Weight"] = "0.1" };

-- UNDERWEAR
TweakItemData["Base.Bikini_TINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Bikini_Pattern01"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Boxers_White"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Boxers_Silk_Black"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Boxers_Silk_Red"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Boxers_RedStripes"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Boxers_Hearts"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Briefs_White"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Briefs_AnimalPrints"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Corset"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Corset_Black"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Corset_Red"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Corset_Medical"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Briefs_SmallTrunks_WhiteTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Briefs_SmallTrunks_Black"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Briefs_SmallTrunks_Blue"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Briefs_SmallTrunks_Red"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Bra_Strapless_White"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Bra_Strapless_Black"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Bra_Strapless_FrillyBlack"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Bra_Strapless_FrillyPink"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Bra_Strapless_FrillyRed"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Bra_Strapless_RedSpots"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Bra_Strapless_AnimalPrint"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Bra_Straps_White"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Bra_Straps_Black"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Bra_Straps_FrillyBlack"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Bra_Straps_FrillyPink"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Bra_Straps_FrillyRed"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Bra_Straps_AnimalPrint"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Underpants_White"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Underpants_Black"] = { ["Weight"] = "0.1" };
TweakItemData["Base.FrillyUnderpants_Black"] = { ["Weight"] = "0.1" };
TweakItemData["Base.FrillyUnderpants_Pink"] = { ["Weight"] = "0.1" };
TweakItemData["Base.FrillyUnderpants_Red"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Underpants_RedSpots"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Underpants_AnimalPrint"] = { ["Weight"] = "0.1" };

-- FACE
TweakItemData["Base.Hat_BalaclavaFull"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_DustMask"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_GasMask"] = { ["Weight"] = "0.1" };
TweakItemData["Base.HockeyMask"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_SurgicalMask_Blue"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_SurgicalMask_Green"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BalaclavaFace"] = { ["Weight"] = "0.1" };
TweakItemData["Base.WeldingMask"] = { ["Weight"] = "0.1" };

-- HAT
TweakItemData["Base.Hat_BaseballCap"] = { ["Weight"] = "0.1" };
TweakItemData["Base.HatBaseballCap_Reverse"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BaseballCapKY"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BaseballCapKY_Reverse"] = { ["Weight"] = "0.1" };
TweakItemData["Base.HatBaseballCapKY_Red"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BaseballCapBlue"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BaseballCapBlue_Reverse"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BaseballCapRed"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BaseballCapRed_Reverse"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BaseballCapGreen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BaseballCapGreen_Reverse"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BaseballCapArmy"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_Beany"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_Beret"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BeretArmy"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BonnieHat"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BonnieHat_CamoGreen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BucketHat"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BunnyEarsBlack"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BunnyEarsWhite"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_ChefHat"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_Cowboy"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_EarMuffs"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_EarMuff_Protectors"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_FastFood"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_Fedora"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_Fedora_Delmonte"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_GolfHat"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_GolfHatTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_FastFood_IceCream"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_SurgicalCap_Blue"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_SurgicalCap_Green"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_NewspaperHat"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_PartyHat_Stars"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_PartyHat_TINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_PeakedCapArmy"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_Police_Grey"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_Police"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_Raccoon"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_Ranger"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_SantaHat"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_SantaHatGreen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_ShowerCap"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_FastFood_Spiffo"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_SummerHat"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_TinFoilHat"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_VisorBlack"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_VisorRed"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_VisorWhiteTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_WeddingVeil"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_WinterHat"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_WoolyHat"] = { ["Weight"] = "0.1" };

-- HELMETS
TweakItemData["Base.Hat_SPHhelmet"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BaseballHelmet_KY"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BaseballHelmet_Rangers"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BaseballHelmet_Z"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BicycleHelmet"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BoxingRed"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_BoxingBlue"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_CrashHelmet"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_Fireman"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_FootballHelmet"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_HardHat"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_HockeyHelmet"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_JockeyHelmet01"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_JockeyHelmet02"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_JockeyHelmet03"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_JockeyHelmet04"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_JockeyHelmet05"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_JockeyHelmet06"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_Army"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_HardHat_Miner"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_CrashHelmetFULL"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_NBCmask"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_CrashHelmet_Police"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_RidingHelmet"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_RiotHelmet"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_Spiffo"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Hat_CrashHelmet_Stars"] = { ["Weight"] = "0.1" };

-- NECK
TweakItemData["Base.Scarf_White"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Scarf_StripeBlackWhite"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Scarf_StripeBlueWhite"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Scarf_StripeRedWhite"] = { ["Weight"] = "0.1" };

-- SHIRTS
TweakItemData["Base.Shirt_Baseball_KY"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_Baseball_Rangers"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_Baseball_Z"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_BoobTube"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_BoobTubeSmall"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_BowlingBlue"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_BowlingBrown"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_BowlingGreen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_BowlingLimeGreen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_BowlingPink"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_BowlingWhite"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_CamoDesert"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_CamoGreen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_CamoUrban"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_CropTopNoArmTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_CropTopTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_Denim"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_FormalWhite"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_FormalWhite_ShortSleeve"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_HawaiianTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_HawaiianRed"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_Jockey01"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_Jockey02"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_Jockey03"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_Jockey04"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_Jockey05"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_Jockey06"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_Lumberjack"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_OfficerWhite"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_PoliceBlue"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_PoliceGrey"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_Priest"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_PrisonGuard"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_Ranger"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_Scrubs"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Shirt_Workman"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_ArmyGreen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_CamoDesert"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_CamoGreen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_CamoUrban"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Fossoil"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Gas2Go"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_ThunderGas"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Rock"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_McCoys"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_PileOCrepe"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_PizzaWhirled"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_BusinessSpiffo"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_ValleyStation"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_DefaultDECAL"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_DefaultDECAL_TINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_DefaultTEXTURE"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_DefaultTEXTURE_TINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_WhiteTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_PoloTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_IndieStoneDECAL"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_PoliceBlue"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_PoliceGrey"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_PoloStripedTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Profession_FiremanBlue"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Profession_FiremanRed"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Profession_FiremanRed02"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Profession_FiremaWhite"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Profession_PoliceBlue"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Profession_PoliceWhite"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Profession_RangerBrown"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Profession_RangerGreen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Profession_VeteranGreen"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Profession_VeteranRed"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Ranger"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Scrubs"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_SpiffoDECAL"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_Sport"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_SportDECAL"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_WhiteLongSleeve"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Tshirt_WhiteLongSleeveTINT"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Vest_DefaultTEXTURE"] = { ["Weight"] = "0.1" };
TweakItemData["Base.Vest_DefaultTEXTURE_TINT"] = { ["Weight"] = "0.1" };

-- SCRAP ARMOR
TweakItemData["ScrapArmor(new version).ScrapHandPlate2R"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapHandPlate2L"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapHandPlateR"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapHandPlateL"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapHandPlateStuddedR"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapHandPlateStuddedL"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).Hat_ScrapKettleHelmet"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).Hat_ScrapHelmet"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).Hat_ScrapHelmetopen"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).Hat_MotorcycleHelmet2"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).Hat_WelderMask2"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).Hat_MotorcycleHelmet2open"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).Hat_Rebreather"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapKiltSign"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapKiltPlated"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapKiltStudded"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapKilt"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapLegPadL"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapLegPadR"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapLegPadBoltsL"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapLegPadBoltsR"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapLegPadSign2L"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapLegPadSign2R"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapLegPadSignL"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapLegPadSignR"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapPauldrons"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapPauldrons2"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapPauldrons2Studded"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapShinPlateR"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapShinPlateL"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapShinPlateStuddedR"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapShinPlateStuddedL"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapShinPlate2R"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapShinPlate2L"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapShoulderPadL"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapShoulderPadR"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapShoulderPadSawL"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapShoulderPadSawR"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapShoulderPadBoltsL"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapShoulderPadBoltsR"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapShoulderPadSignL"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapShoulderPadSignR"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapVest"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapVestPlated"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapVestSign"] = { ["Weight"] = "0.1" };
TweakItemData["ScrapArmor(new version).ScrapVestStudded"] = { ["Weight"] = "0.1" };

-- BRITAS ARMOR

TweakItemData["Brita_2.Armor_Defender"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Plate_Carrier"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Armor_6B13"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Jacket_Heather"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Sheriff_Vest"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Sheriff_Vest_Full"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_PSGT_Helmet"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_PSGT_Helmet_Camo"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_PSGT_Visor"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_PSGT_Visor_UP"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Riot_Visor"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Riot_Visor_UP"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_PSGT_Neck"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Sniper_Pack"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_ARVN_Rucksack"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_ST53_Set"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_SCBA"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_ZIP"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_SSO"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Savotta"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Bush"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Hunting"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Radio_Pack"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Tactical_Alice"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Cat_Pack"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Robbie_Pack"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_M2A1_Pack"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Tactical_Belt_Front"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Tactical_Belt_Back"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Duty_Belt_Front"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Duty_Belt_Back"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Beret_Tactical"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Beret_Tactical_Only"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Beret_Tactical_Headset"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_D3M"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_D3M_Loose"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Blackhawk"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Blackhawk_Loose"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_X_Vest"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_X_Vest_Loose"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_SKS_Vest"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_SKS_Vest_Loose"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_AK_Vest"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_AK_Vest_Loose"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Combat_Jumper"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Combat_Pants"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Ela_Jacket"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Ela_Pants"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Ela_Hat"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Ela_Hat_Only"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Ela_Headset"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_FAST_Opscore"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_880_Helmet"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_880_Visor"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_880_Visor_UP"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Fire_Jacket"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Fire_Pants"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_MCU_GasMask"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_M45_GasMask"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_M50"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_FM53"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_MSA_Gas_Mask"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_MSA_Gas_Mask_AMP"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Gentex_Helmet"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_HGU56"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Glasses_X1000"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Glasses_X1000_OFF"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Glasses_Napier"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Glasses_Crewman_Goggles"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Glasses_Crewman_Goggles_OFF"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_HGU56_Visor"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Gorka_Jacket"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Gorka_Jacket2"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Gorka_Jacket3"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Gorka_Pants"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Gorka_Pants2"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Gorka_Pants3"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Gorka_Jacket_New"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Gorka_Pants_New"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Tactical_Boonie"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Tactical_Boonie_Fold"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Lisa_Cap"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Tactical_Cap"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Tactical_Cap_Camo"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Patrol_Cap"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Tactical_Beret"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Suit_Chempak"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Sordin"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Astrocom"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Face_Shield"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Helmet_Headset"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_HGU56_Shield"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Sniper_Hood"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Shemagh_Half"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Sniper_Suit"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Sniper_Suit_Off"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Armor_Juggernaut"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Armor_Arm"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Armor_Foot"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Juggernaut_Bag"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Killa_Jacket"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Killa_Pants"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_M1_Helmet"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_M1_Helmet_Ori"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Maska"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Killa"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Maska_Visor"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Maska_Visor2"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Maska_Visor_UP"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Maska_Visor2_UP"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Killa_Visor"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Killa_Visor_UP"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Skirt_Nurse"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Pants_Yoga"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Turtleneck"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Belly_Turtleneck"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.S_Tank_Top"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Y_Shirts"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Y_Shirts_Long"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Skirt_Office"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Skirt_Office_Long"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Office_Sweater"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Office_Sweater_Long"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Pants_Adidas"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Jacket_Adidas"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_MX_Helmet"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_MX_Helmet_Glass"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Sheriff_Jumper"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Police_Jumper"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_PVS_5"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_PVS_5_OFF"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_PVS15"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_PVS15_UP"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Sam_NV"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Sam_NV_OFF"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_PVS15_ON"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_PVS15_OFF"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_PVS15_Harness_ON"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_PVS15_Harness_OFF"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_NV18_ON"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_NV18_OFF"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_NV18_Harness_ON"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_NV18_Harness_OFF"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Rabbit_Suit"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Hat_Rabbit"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Smersh_Vest"] = { ["Weight"] = "0.1" };
TweakItemData["Brita_2.Bag_Smersh_Vest_Loose"] = { ["Weight"] = "0.1" };

-- UNDEAD SURVIVOR

TweakItemData["UndeadSuvivor.PrepperMask"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.PrepperHelmet"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.PrepperVest"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.PrepperVestPacked"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.PrepperBags"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.PrepperJacket"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.PrepperTrousers"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.PrepperTrousersTucked"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.StalkerCloak"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.StalkerCloakDOWN"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.StalkerMask"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.StalkerJacket"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.StalkerTrousers"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.StalkerTrousersTucked"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.StalkerBoots"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.StalkerGloves"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.NomadParka"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.NomadParkaDOWN"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.OminousNomadParka"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.OminousNomadParkaDOWN"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.NomadBackpack"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.NomadMask"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.OminousNomadMask"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.NomadBoots"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.NomadTrousers"] = { ["Weight"] = "0.1" };
TweakItemData["UndeadSuvivor.NomadTrousersTucked"] = { ["Weight"] = "0.1" };