require "Items/Distributions"
require "Items/ItemPicker"
require "Vehicles/VehicleDistributions"

table.insert(ProceduralDistributions.list.ArmySurplusTools.items, "PA_TrenchKnife")
table.insert(ProceduralDistributions.list.ArmySurplusTools.items, 0.25)	
table.insert(ProceduralDistributions.list.ArmySurplusTools.items, "PA_TrenchKnifeB")
table.insert(ProceduralDistributions.list.ArmySurplusTools.items, 0.25)	
table.insert(ProceduralDistributions.list.ArmySurplusTools.items, "PA_TrenchKnifeC")
table.insert(ProceduralDistributions.list.ArmySurplusTools.items, 0.25)	

table.insert(ProceduralDistributions.list.ClosetShelfGeneric.items, "PA_TrenchKnife")
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.items, 0.0025)
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.items, "PA_TrenchKnifeB")
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.items, 0.0025)
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.items, "PA_TrenchKnifeC")
table.insert(ProceduralDistributions.list.ClosetShelfGeneric.items, 0.0052)

table.insert(ProceduralDistributions.list.GarageFirearms.items, "PA_TrenchKnife")
table.insert(ProceduralDistributions.list.GarageFirearms.items, 0.25)
table.insert(ProceduralDistributions.list.GarageFirearms.items, "PA_TrenchKnifeB")
table.insert(ProceduralDistributions.list.GarageFirearms.items, 0.25)
table.insert(ProceduralDistributions.list.GarageFirearms.items, "PA_TrenchKnifeC")
table.insert(ProceduralDistributions.list.GarageFirearms.items, 0.25)

table.insert(ProceduralDistributions.list.GunStoreShelf.items, "PA_TrenchKnife")
table.insert(ProceduralDistributions.list.GunStoreShelf.items, 0.025)
table.insert(ProceduralDistributions.list.GunStoreShelf.items,"PA_TrenchKnifeB")
table.insert(ProceduralDistributions.list.GunStoreShelf.items, 0.025)
table.insert(ProceduralDistributions.list.GunStoreShelf.items,"PA_TrenchKnifeC")
table.insert(ProceduralDistributions.list.GunStoreShelf.items, 0.025)

table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "PA_TrenchKnife")
table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.1)
table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "PA_TrenchKnifeB")
table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.1)
table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, "PA_TrenchKnifeC")
table.insert(ProceduralDistributions.list.LockerArmyBedroom.items, 0.1)


table.insert(ProceduralDistributions.list.PawnShopKnives.items,"PA_TrenchKnife")
table.insert(ProceduralDistributions.list.PawnShopKnives.items, 0.1)
table.insert(ProceduralDistributions.list.PawnShopKnives.items,"PA_TrenchKnifeB")
table.insert(ProceduralDistributions.list.PawnShopKnives.items, 0.1)
table.insert(ProceduralDistributions.list.PawnShopKnives.items,"PA_TrenchKnifeC")
table.insert(ProceduralDistributions.list.PawnShopKnives.items, 0.1)

table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "PA_TrenchKnife")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 0.005)
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "PA_TrenchKnifeB")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 0.005)
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "PA_TrenchKnifeC")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 0.005)

table.insert(ProceduralDistributions.list.MeleeWeapons.items, "PA_TrenchKnife")
table.insert(ProceduralDistributions.list.MeleeWeapons.items, 0.5)	
table.insert(ProceduralDistributions.list.MeleeWeapons.items, "PA_TrenchKnifeB")
table.insert(ProceduralDistributions.list.MeleeWeapons.items, 0.5)
table.insert(ProceduralDistributions.list.MeleeWeapons.items, "PA_TrenchKnifeC")
table.insert(ProceduralDistributions.list.MeleeWeapons.items, 0.5)

table.insert(ProceduralDistributions.list.PlankStashGun.items,  "PA_TrenchKnife")
table.insert(ProceduralDistributions.list.PlankStashGun.items, 0.1)
table.insert(ProceduralDistributions.list.PlankStashGun.items,  "PA_TrenchKnifeB")
table.insert(ProceduralDistributions.list.PlankStashGun.items, 0.1)
table.insert(ProceduralDistributions.list.PlankStashGun.items,  "PA_TrenchKnifeC")
table.insert(ProceduralDistributions.list.PlankStashGun.items, 0.1)

table.insert(SuburbsDistributions.Bag_WeaponBag.items, "PA_TrenchKnife")
table.insert(SuburbsDistributions.Bag_WeaponBag.items, 0.5)	
table.insert(SuburbsDistributions.Bag_WeaponBag.items,"PA_TrenchKnifeB")
table.insert(SuburbsDistributions.Bag_WeaponBag.items, 0.5)		
table.insert(SuburbsDistributions.Bag_WeaponBag.items,"PA_TrenchKnifeC")
table.insert(SuburbsDistributions.Bag_WeaponBag.items, 0.5)	

table.insert(SuburbsDistributions.Bag_SurvivorBag.items, "PA_TrenchKnife")
table.insert(SuburbsDistributions.Bag_SurvivorBag.items, 0.5)
table.insert(SuburbsDistributions.Bag_SurvivorBag.items, "PA_TrenchKnifeB")
table.insert(SuburbsDistributions.Bag_SurvivorBag.items, 0.5)
table.insert(SuburbsDistributions.Bag_SurvivorBag.items, "PA_TrenchKnifeC")
table.insert(SuburbsDistributions.Bag_SurvivorBag.items, 0.5)

table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items, "PA_TrenchKnife")
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items, 0.05)	
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items,"PA_TrenchKnifeB")
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items, 0.05)	
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items,"PA_TrenchKnifeC")
table.insert(SuburbsDistributions.SurvivorCache1.SurvivorCrate.items, 0.05)	
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, "PA_TrenchKnife")
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, 0.05)		
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items,"PA_TrenchKnifeB")
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, 0.05)		
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items,"PA_TrenchKnifeC")
table.insert(SuburbsDistributions.SurvivorCache2.SurvivorCrate.items, 0.05)	

table.insert(VehicleDistributions.SurvivalistTruckBed.items, "PA_TrenchKnife")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.25)	
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "PA_TrenchKnifeB")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.25)	
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "PA_TrenchKnifeC")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.25)