require "Hotbar/ISHotbarAttachDefinition"
if not ISHotbarAttachDefinition then
    return
end


local S_Belta = {
	type = "S_Belta",
	name = "S_Belta", 
	animset = "belt left",
	attachments = {
		Rope 				= "S_Belta Left",
		SheetRope			= "S_Belta Left",		
		FlareGun 			= "S_Belta Left",
		Explosive 			= "S_Belta Left",
		AuthenticExplosive  = "S_Belta Left",		
		GasMask 			= "S_Belta Left",		
		Walkie 				= "S_Belta Left",
		Hammer 				= "S_Belta Left",
		Screwdriver 		= "S_Belta Left",
		Knife			 	= "S_Belta Left",
		Saucepan 			= "S_Belta Left",	
		Pan 				= "S_Belta Left",
		Wrench 				= "S_Belta Left",		
		MeatCleaver 		= "S_Belta Left",
		Gear 				= "S_Belta Left",
        Holster             = "S_Belta Left",
        BigWeapon           = "S_Belta Left",
        Nightstick          = "S_Belta Left",
        BigBlade            = "S_Belta Left",
        Racket              = "S_Belta Left",
        Guitar              = "S_Belta Left",
        GuitarAcoustic      = "S_Belta Left",
        Shovel              = "S_Belta Left",
        Rifle               = "S_Belta Left",
	},
}
table.insert(ISHotbarAttachDefinition, S_Belta);

local S_Beltb = {
	type = "S_Beltb",
	name = "S_Beltb", 
	animset = "belt right",
	attachments = {
		Rope 				= "S_Beltb Left",
		SheetRope			= "S_Beltb Left",		
		FlareGun 			= "S_Beltb Left",
		Explosive 			= "S_Beltb Left",
		AuthenticExplosive  = "S_Beltb Left",		
		GasMask 			= "S_Beltb Left",		
		Walkie 				= "S_Beltb Left",
		Hammer 				= "S_Beltb Left",
		Screwdriver 		= "S_Beltb Left",
		Knife			 	= "S_Beltb Left",
		Saucepan 			= "S_Beltb Left",	
		Pan 				= "S_Beltb Left",
		Wrench 				= "S_Beltb Left",		
		MeatCleaver 		= "S_Beltb Left",
		Gear 				= "S_Beltb Left",
        Holster             = "S_Beltb Left",
        BigWeapon           = "S_Beltb Left",
        Nightstick          = "S_Beltb Left",
        BigBlade            = "S_Beltb Left",
        Racket              = "S_Beltb Left",
        Guitar              = "S_Beltb Left",
        GuitarAcoustic      = "S_Beltb Left",
        Shovel              = "S_Beltb Left",
        Rifle               = "S_Beltb Left",
	},
}
table.insert(ISHotbarAttachDefinition, S_Beltb);

local S_Beltc = {
	type = "S_Beltc",
	name = "S_Beltc", 
	animset = "back",
	attachments = {
		Rope 				= "S_Beltc Left",
		SheetRope			= "S_Beltc Left",		
		FlareGun 			= "S_Beltc Left",
		Explosive 			= "S_Beltc Left",
		AuthenticExplosive  = "S_Beltc Left",		
		GasMask 			= "S_Beltc Left",		
		Walkie 				= "S_Beltc Left",
		Hammer 				= "S_Beltc Left",
		Screwdriver 		= "S_Beltc Left",
		Knife			 	= "S_Beltc Left",
		Saucepan 			= "S_Beltc Left",	
		Pan 				= "S_Beltc Left",
		Wrench 				= "S_Beltc Left",		
		MeatCleaver 		= "S_Beltc Left",
		Gear 				= "S_Beltc Left",
        Holster             = "S_Beltc Left",
        BigWeapon           = "S_Beltc Left",
        Nightstick          = "S_Beltc Left",
        BigBlade            = "S_Beltc Left",
        Racket              = "S_Beltc Left",
        Guitar              = "S_Beltc Left",
        GuitarAcoustic      = "S_Beltc Left",
        Shovel              = "S_Beltc Left",
        Rifle               = "S_Beltc Left",
	},
}
table.insert(ISHotbarAttachDefinition, S_Beltc);

local S_Beltd = {
	type = "S_Beltd",
	name = "S_Beltd", 
	animset = "belt left",
	attachments = {
		Rope 				= "S_Beltd Left",
		SheetRope			= "S_Beltd Left",		
		FlareGun 			= "S_Beltd Left",
		Explosive 			= "S_Beltd Left",
		AuthenticExplosive  = "S_Beltd Left",		
		GasMask 			= "S_Beltd Left",		
		Walkie 				= "S_Beltd Left",
		Hammer 				= "S_Beltd Left",
		Screwdriver 		= "S_Beltd Left",
		Knife			 	= "S_Beltd Left",
		Saucepan 			= "S_Beltd Left",	
		Pan 				= "S_Beltd Left",
		Wrench 				= "S_Beltd Left",		
		MeatCleaver 		= "S_Beltd Left",
		Gear 				= "S_Beltd Left",
        Holster             = "S_Beltd Left",
        BigWeapon           = "S_Beltd Left",
        Nightstick          = "S_Beltd Left",
        BigBlade            = "S_Beltd Left",
        Racket              = "S_Beltd Left",
        Guitar              = "S_Beltd Left",
        GuitarAcoustic      = "S_Beltd Left",
        Shovel              = "S_Beltd Left",
        Rifle               = "S_Beltd Left",
	},
}
table.insert(ISHotbarAttachDefinition, S_Beltd);

local S_Belte = {
	type = "S_Belte",
	name = "S_Belte", 
	animset = "belt right",
	attachments = {
		Rope 				= "S_Belte Left",
		SheetRope			= "S_Belte Left",		
		FlareGun 			= "S_Belte Left",
		Explosive 			= "S_Belte Left",
		AuthenticExplosive  = "S_Belte Left",		
		GasMask 			= "S_Belte Left",		
		Walkie 				= "S_Belte Left",
		Hammer 				= "S_Belte Left",
		Screwdriver 		= "S_Belte Left",
		Knife			 	= "S_Belte Left",
		Saucepan 			= "S_Belte Left",	
		Pan 				= "S_Belte Left",
		Wrench 				= "S_Belte Left",		
		MeatCleaver 		= "S_Belte Left",
		Gear 				= "S_Belte Left",
        Holster             = "S_Belte Left",
        BigWeapon           = "S_Belte Left",
        Nightstick          = "S_Belte Left",
        BigBlade            = "S_Belte Left",
        Racket              = "S_Belte Left",
        Guitar              = "S_Belte Left",
        GuitarAcoustic      = "S_Belte Left",
        Shovel              = "S_Belte Left",
        Rifle               = "S_Belte Left",
	},
}
table.insert(ISHotbarAttachDefinition, S_Belte);

local S_Beltf = {
	type = "S_Beltf",
	name = "S_Beltf", 
	animset = "back",
	attachments = {
		Rope 				= "S_Beltf Left",
		SheetRope			= "S_Beltf Left",		
		FlareGun 			= "S_Beltf Left",
		Explosive 			= "S_Beltf Left",
		AuthenticExplosive  = "S_Beltf Left",		
		GasMask 			= "S_Beltf Left",		
		Walkie 				= "S_Beltf Left",
		Hammer 				= "S_Beltf Left",
		Screwdriver 		= "S_Beltf Left",
		Knife			 	= "S_Beltf Left",
		Saucepan 			= "S_Beltf Left",	
		Pan 				= "S_Beltf Left",
		Wrench 				= "S_Beltf Left",		
		MeatCleaver 		= "S_Beltf Left",
		Gear 				= "S_Beltf Left",
        Holster             = "S_Beltf Left",
        BigWeapon           = "S_Beltf Left",
        Nightstick          = "S_Beltf Left",
        BigBlade            = "S_Beltf Left",
        Racket              = "S_Beltf Left",
        Guitar              = "S_Beltf Left",
        GuitarAcoustic      = "S_Beltf Left",
        Shovel              = "S_Beltf Left",
        Rifle               = "S_Beltf Left",
	},
}
table.insert(ISHotbarAttachDefinition, S_Beltf);

local S_Beltg = {
	type = "S_Beltg",
	name = "S_Beltg", 
	animset = "belt left",
	attachments = {
		Rope 				= "S_Beltg Left",
		SheetRope			= "S_Beltg Left",		
		FlareGun 			= "S_Beltg Left",
		Explosive 			= "S_Beltg Left",
		AuthenticExplosive  = "S_Beltg Left",		
		GasMask 			= "S_Beltg Left",		
		Walkie 				= "S_Beltg Left",
		Hammer 				= "S_Beltg Left",
		Screwdriver 		= "S_Beltg Left",
		Knife			 	= "S_Beltg Left",
		Saucepan 			= "S_Beltg Left",	
		Pan 				= "S_Beltg Left",
		Wrench 				= "S_Beltg Left",		
		MeatCleaver 		= "S_Beltg Left",
		Gear 				= "S_Beltg Left",
        Holster             = "S_Beltg Left",
        BigWeapon           = "S_Beltg Left",
        Nightstick          = "S_Beltg Left",
        BigBlade            = "S_Beltg Left",
        Racket              = "S_Beltg Left",
        Guitar              = "S_Beltg Left",
        GuitarAcoustic      = "S_Beltg Left",
        Shovel              = "S_Beltg Left",
        Rifle               = "S_Beltg Left",
	},
}
table.insert(ISHotbarAttachDefinition, S_Beltg);

local S_Belth = {
	type = "S_Belth",
	name = "S_Belth", 
	animset = "belt right",
	attachments = {
		Rope 				= "S_Belth Left",
		SheetRope			= "S_Belth Left",		
		FlareGun 			= "S_Belth Left",
		Explosive 			= "S_Belth Left",
		AuthenticExplosive  = "S_Belth Left",		
		GasMask 			= "S_Belth Left",		
		Walkie 				= "S_Belth Left",
		Hammer 				= "S_Belth Left",
		Screwdriver 		= "S_Belth Left",
		Knife			 	= "S_Belth Left",
		Saucepan 			= "S_Belth Left",	
		Pan 				= "S_Belth Left",
		Wrench 				= "S_Belth Left",		
		MeatCleaver 		= "S_Belth Left",
		Gear 				= "S_Belth Left",
        Holster             = "S_Belth Left",
        BigWeapon           = "S_Belth Left",
        Nightstick          = "S_Belth Left",
        BigBlade            = "S_Belth Left",
        Racket              = "S_Belth Left",
        Guitar              = "S_Belth Left",
        GuitarAcoustic      = "S_Belth Left",
        Shovel              = "S_Belth Left",
        Rifle               = "S_Belth Left",
	},
}
table.insert(ISHotbarAttachDefinition, S_Belth);

local S_Belti = {
	type = "S_Belti",
	name = "S_Belti", 
	animset = "back",
	attachments = {
		Rope 				= "S_Belti Left",
		SheetRope			= "S_Belti Left",		
		FlareGun 			= "S_Belti Left",
		Explosive 			= "S_Belti Left",
		AuthenticExplosive  = "S_Belti Left",		
		GasMask 			= "S_Belti Left",		
		Walkie 				= "S_Belti Left",
		Hammer 				= "S_Belti Left",
		Screwdriver 		= "S_Belti Left",
		Knife			 	= "S_Belti Left",
		Saucepan 			= "S_Belti Left",	
		Pan 				= "S_Belti Left",
		Wrench 				= "S_Belti Left",		
		MeatCleaver 		= "S_Belti Left",
		Gear 				= "S_Belti Left",
        Holster             = "S_Belti Left",
        BigWeapon           = "S_Belti Left",
        Nightstick          = "S_Belti Left",
        BigBlade            = "S_Belti Left",
        Racket              = "S_Belti Left",
        Guitar              = "S_Belti Left",
        GuitarAcoustic      = "S_Belti Left",
        Shovel              = "S_Belti Left",
        Rifle               = "S_Belti Left",
	},
}
table.insert(ISHotbarAttachDefinition, S_Belti);